name = "PhysicalOptics"
uuid = "0a60f967-c2e9-4ead-9e3e-647388820460"
authors = ["Felix Wechsler <fxw+github@mailbox.org>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ChainRulesCore = "0.9"
FFTW = "1.2"
Interpolations = "0.13"
QuadGK = "2.4.1"
SpecialFunctions = "1"
julia = "1.5"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Interpolations", "SpecialFunctions"]
